
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.0a1'
version_full = 'acdf90f8db25e364845585a7c9fce2986588d3d5'


def get_versions(default={}, verbose=False):
        return {'version': version_version, 'full': version_full}
